// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB02-NcHQAvslXdk1mf7AtJSfoHKTedVFc',
    appId: '1:212377349769:web:33af79d0029c0334fea058',
    messagingSenderId: '212377349769',
    projectId: 'linkproject-90c94',
    authDomain: 'linkproject-90c94.firebaseapp.com',
    storageBucket: 'linkproject-90c94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9Qb2lHXMJoKeec_wgBlR3IttuxrlFcE',
    appId: '1:212377349769:android:15568ff6f226c9d5fea058',
    messagingSenderId: '212377349769',
    projectId: 'linkproject-90c94',
    storageBucket: 'linkproject-90c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVM7xbGK9hpIWMXoBlZwx92gNRcjr1CM',
    appId: '1:212377349769:ios:2d4f0aa93e3b27abfea058',
    messagingSenderId: '212377349769',
    projectId: 'linkproject-90c94',
    storageBucket: 'linkproject-90c94.appspot.com',
    iosClientId: '212377349769-serb058f74fr1epgivvp256dadt3l8mo.apps.googleusercontent.com',
    iosBundleId: 'com.denizbora.linkProject',
  );
}
